
export const config = {
    SERVER_URL_AUTH_MICROSERVICE: process.env.REACT_APP_SERVER_URL_AUTH_MICROSERVICE,
    SERVER_URL_PHOTO_MICROSERVICE: process.env.REACT_APP_SERVER_URL_PHOTO_MICROSERVICE,
    SERVER_URL_ALBUM_MICROSERVICE: process.env.REACT_APP_SERVER_URL_ALBUM_MICROSERVICE
}